---
name: Running Pipeline

on:
  pull_request:
    branches: ['main']

jobs:
  tests:
    name: Executing pipeline's steps
    runs-on: ubuntu-latest
    steps:
      - name: Run checkout on current branch
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python -m unittest discover ./tests/url/
    